image: docker:stable
stages:
  - build-test
  - docker_build
  - deploy
  
build_nodejs:
  image: node:16-alpine
  stage: build-test
  tags:
    - benja-minikube
  script:
    - ls && pwd
    - npm install
    # - npm test

docker_build_job:
  image: docker:latest
  stage: docker_build
  tags:
    - benja-minikube
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/bentangpradana/ci-cd-for-kubernetes:$CI_PIPELINE_ID .
    - docker push registry.gitlab.com/bentangpradana/ci-cd-for-kubernetes:$CI_PIPELINE_ID
    - docker rmi --force  $(docker images | grep ci-cd-for-kubernetes | awk '{print $3}')
  only:
    - main

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - benja-minikube
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no -p 2222 $SERVER_USER@$SERVER_IP " cd /home/benja/new-folder/ci-cd-for-kubernetes && git pull origin main && cd /home/benja/new-folder/ci-cd-for-kubernetes/deployment/ && sed -i "s/IMAGE_TAG/$CI_PIPELINE_ID/g" deployment.yaml && kubectl apply -f deployment.yaml"

  only:
    - main




